Properly treat non-movers in EDGT lyon adisp data
eqasim-org/ile-de-france pull request #169
Opened 2023-04-07 14:05 UTC by LeonardoLuquezi

* filter edgt lyon adisp data
* update edgt lyon adisp feature

2023-04-11 19:54 UTC, sebhoerl commented
Thanks! Somehow this looks familar. This is something that was already fixed for Nantes, isn't it? I'll merge as soon as #166 goes through.

2023-04-13 09:10 UTC, LeonardoLuquezi commented
Yes, that's right. It's the same treatment we do with the data from Nantes.

2023-04-18 09:06 UTC, sebhoerl requested changes
Please add a note on top of `CHANGELOG.md`:

> Properly treat non-movers in EDGT Lyon ADISP data

2023-04-18 09:06 UTC, sebhoerl commented on data/hts/edgt_lyon/cleaned_adisp.py
> +    # People that awnsered the travel questionary section but stayed at home (number_of_trips = 0)
awnsered > answered

2023-04-20 10:02 UTC, sebhoerl approved these changes

2023-04-20 10:02 UTC, sebhoerl commented
Thansk a lot!

2023-04-20 10:03 UTC, merged