urban units option for ENTD
eqasim-org/ile-de-france pull request #209
Opened 2024-01-30 10:22 UTC by aburianne

ENTD (national mobility survey) can be used to generate synthetic population (with Synpop) over any metropolitan french territory. It is mostly used whether there are no available EMD or EDGT (local mobility survey with higer sampling). 

ENTD is (main method) filtered by departments (i.e.: Gironde-33, Paris-75) composing the survey area, leaving us with critical low sampling issues. Therefore we aim to change approach on sampling and parameters inputs for agents mobility behaviors.

Our proposal is to keep all of metropolitan France (NO department filter) and to apply a typology based on 4 classes :

- central city 
- suburbs 
- isolated city
- rural / countryside

Doing so, we assume same mobility behaviors patterns within classes, i.e. : Lyon, Bordeaux, Marseille... and significant deviation between classes. 

This 4 classes typology is computed and __[open source distributed by INSEE](https://www.insee.fr/fr/information/4802589)__. It is refered to as "Unités Urbaines" (UU). INSEE internal main use of this dataset is to adapt statistics methods to context. The data comes as Microsoft Excel (.xlsx) worksheet with a 2010 and a 2020 version with official geographical code milleisim options.

The UU typology being availble both in ENTD and official geographical codes for all of metropolitan France it is suitable for the process.

2024-01-30 10:33 UTC, aburianne commented on matsim/runtime/eqasim.py
Changed for use with Tarek developments on mode choice (but not shure of what version to keep)

2024-01-30 10:35 UTC, aburianne commented on data/spatial/uu.py
had issue with excel file when reading (fixes by manually open / save / close in excel). Maybe a different library or file fix?

2024-03-18 08:39 UTC, sebhoerl requested changes

2024-03-18 08:39 UTC, sebhoerl commented on .gitignore
> +config_bordeaux*.yml
Remove

2024-03-18 08:39 UTC, sebhoerl commented on config.yml
> +  - matsim.output # Uncomment, if you want to run the full simulation (you'll need Java for that)
Reset

2024-03-18 08:39 UTC, sebhoerl commented on config_bordeaux_0.1.yml
> +## Synthetic population pipeline for Île-de-France
Remove file

2024-03-18 08:39 UTC, sebhoerl commented on data/census/cleaned.py
> +    uu = context.stage("data.spatial.uu")
change to df_urban_type

2024-03-18 08:39 UTC, sebhoerl commented on data/census/cleaned.py
> +    # UU match
"Impute urban type"

2024-03-18 08:39 UTC, sebhoerl commented on data/census/cleaned.py
> +    df.loc[df["commune_id"] == "undefined","type_uu"] = "rural"
I would call "rural" as "none", because it does not have an "urban type"

2024-03-18 08:39 UTC, sebhoerl commented on data/census/cleaned.py
> +        "consumption_units", "socioprofessional_class","type_uu"
Rename column to urban_type

2024-03-18 08:39 UTC, sebhoerl commented on data/hts/entd/cleaned.py
> +    df_households["type_uu"] = df_households["numcom_UU2010"].replace({"B":"suburb","C":"central_city","I":"isolated_city","R":"rural"})
rural -> none

2024-03-18 08:39 UTC, sebhoerl commented on data/hts/entd/cleaned.py
> +    assert np.all(~df_households["type_uu"].isna())
column urban_type

2024-03-18 08:39 UTC, sebhoerl commented on data/hts/hts.py
> +    return error_count == 1
Set back to zero, fix if it gives an error

2024-03-18 08:39 UTC, sebhoerl commented on data/hts/hts.py
> +    "consumption_units", "type_uu" # "income_class"
column name

2024-03-18 08:39 UTC, sebhoerl commented on matsim/runtime/eqasim.py
let's update to latest develop

2024-03-18 11:04 UTC, sebhoerl commented
- Cleaned up the code
- I propose to name the attributes `urban_type` and then have either `suburb`, `center_city`, `isolated_city`, but all the remaining zones are `none`

2024-03-18 11:25 UTC, sebhoerl approved these changes

2024-03-18 11:33 UTC, sebhoerl commented
To use the urban type one needs now to
- set `use_urban_type: true` in the configuration (this imputes the information)
- set `matching_attributes: ["urban_type", "*default*"]` this appends the `urban_type` to the default matching attributes

2024-03-18 17:23 UTC, merged