Add alternative source for EDGT Lyon
eqasim-org/ile-de-france pull request #89
Opened 2022-01-10 13:37 UTC by Nitnelav

There is a way to get Lyon EDGT from the ADISP portal : http://www.progedo-adisp.fr/serie_emd.php
It is free for academic use and should be the most straightforward way to get the data.
The data is formatted a bit differently compared to what @sebhoerl got (driectly from CEREMA), so this PR adds the code to read EDGT from this new source.

2022-01-10 20:44 UTC, sebhoerl requested changes
Really nice, could you please look at the few little points?

2022-01-10 20:44 UTC, sebhoerl commented on docs/cases/lyon.md
> +- `data/edgt_lyon_2015/EDGT_AML2015_ZF_GT.TA`
TA or TAB ?

2022-01-10 20:44 UTC, sebhoerl commented on docs/cases/lyon.md
> +  edgt_lyon_source: adisp  # adisp/cerema
Can you add a comment somewhere in the text above to make sure it is clear that one needs to make a choice here?

2022-01-10 20:44 UTC, sebhoerl commented on data/hts/edgt_lyon/filtered.py
> +    edgt_lyon_source = context.config("edgt_lyon_source", "adisp")
Instead of "adisp", can we have a default value "unchosen" ...

2022-01-10 20:44 UTC, sebhoerl commented on data/hts/edgt_lyon/filtered.py
> +    else:
And then here another elif that raises an exception, but explicitly telling the user that the EDGT source needs to be chosen, if the value is still "unchosen". Then we can nicely remind the user to set it :)

2022-01-11 08:36 UTC, Nitnelav commented on docs/cases/lyon.md
> +- `data/edgt_lyon_2015/EDGT_AML2015_ZF_GT.TA`
TAB ;)

2022-01-11 08:40 UTC, Nitnelav commented
I added a small .gitignore update there too, unrelated to the PR but not worth a seperate one either i rekon

2022-01-12 08:35 UTC, sebhoerl approved these changes

2022-01-12 08:36 UTC, merged